//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Sport_Products.Model
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public string ProductArticle { get; set; }
        public string ProductName { get; set; }
        public int ProductUnit { get; set; }
        public double ProductCost { get; set; }
        public int ProductDiscountMax { get; set; }
        public int ProductManufacturer { get; set; }
        public int ProductProvider { get; set; }
        public int ProductCategory { get; set; }
        public int ProductDiscountCurrent { get; set; }
        public int ProductStorageSupply { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImage { get; set; }

        public string ProductImagePath
        {
            get
            {
                string temp;
                if (this.ProductImage != null) 
                {
                    temp = Directory.GetCurrentDirectory() + "/Images/" + this.ProductImage.ToString();
                }
                else
                {
                    temp = "/Resources/picture.png";
                }
                return temp;
            }
        }

        public double ProductDiscountCost
        {
            get
            {
                return Math.Round(this.ProductCost * (100.0 -  this.ProductDiscountCurrent) /100.0, 2);
            }
        }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
